[package]
name = "vs087test"
version = "0.1.0"
authors = ["Craig Prevallet <penguintx@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vsop87 = "2.1.0"
